/*
Random Tester
------------
I developed my random tester by looking at what errors the tester was actually looking for.

Which is to say, it increases a variable called 'state' by looking for a specific random
character each iteration, in the order:

1) '['
2) '('
3) '{'
4) ' '
5) 'a'
6) 'x'
7) '}'
8) ')'
9) ']'

I therefore tried to produce ASCII characters from Decimal Value 32 to 126 for my 
inputChar() function, so that it would produce any of these values. 

For inputString(), I noticed that we were really looking for a 5-character string that
was 'reset' when the error message is reached, so I generated 5 random characters
that were all lowercase alphabetical characters. The 6th character is a null terminator, 
'\0'.

How It Finds the Error
-----------
The random tester finds the error by increasing an int variable called 'state' up to 9.
The critera for increasing the state integer per integer value is:

1) '['
2) '('
3) '{'
4) ' '
5) 'a'
6) 'x'
7) '}'
8) ')'
9) ']'

Once state is 9, the error message is produced once the random string generated
equals 'reset'. The probability of 'reset' being generated by the random string generator 
is quite low, and it took me over 6 million iterations to get to the error message. 
 */