/*
randomhistory.c Assignment 4
CS 362
Matt Walz

For starters, I began development of my random tester by working on the randomization portion of the program. How would I create a random game state, but at the same time test realistic game scenarios? To accomplish this I decided on a game with random characteristics which would occur during an actual game situation. For example, the game state included a number of players between 2 and 4, hand sizes between 1 or 2 (depending on how many cards needed to be in a player's hand to play the card to be tested) and 24 (set at 24 arbitrarily to be a realistic maximum), deck sizes between 0 and 24 (24 as the max to allow for a higher probability of testing deck sizes, or combined deck and discard pile sizes, of 0, 1, etc which would be boundary conditions for the tested cards), and discard pile sizes between 0 and 24 (24 as the max to allow for a higher probability of testing combined deck and discard pile sizes of 0, 1, etc which would be boundary conditions for the tested cards). Each player's hand, deck, and discard piles were also randomly populated with available kingdom cards for that particular game instance (the kingdom cards in the game were randomly selected as well as the supply available for each kingdom card).

By creating these random game states I was able to test the card being played in significantly more feasible scenarios than I was with strictly user-defined tests. And while the coverage of dominion.c did not increase very much (line coverage from 21.64% on manual tester of adventurer card to 24.26% on random tester of adventurer and branch coverage from 25.06% on manual tester to 25.55% on random tester), the range of viable scenario inputs increased dramatically. For example, in the random tester the player playing the card was not always player 1, the player's had different sized hands and decks and those hands and decks were populated with a random assortment of cards as opposed to just the starting number of cards and particular cards prescribed by the manual tester. This significantly improved the ability to check the "correctness" of the card effects. For example in testing the mine card the random tester allowed me to realize there was a distinction in the behavior of the card when the cost of choice2 equaled the maximum allowed cost (cost of choice1 + 3) as compared to when the cost of choice2 was less than the maximum allowed cost. In the manual tester these were not test cases which were distinguished between. This allowed for a bug to be found which might have been missed by the manual testing option.

The other advantage to the random tester is the ability to scale up the number of tests by simply changing the NUM_TESTS variable. This allows for an almost infinite combination of test cases to be tested whereas with the manual tester, upping the number of tests would require either hard coding the new test scenarios into the tester or simply re-running the same test cases multiple times. The random testing option significantly improved the ability to test the card effect/function under numerous test conditions and either validate or invalidate the code's "correctness."
*/